//PRODUCT API ACTIONS
export const FETCHED_REQUEST = 'FETCHED_REQUEST';
export const FETCHED_SUCCESS = 'FETCHED_SUCCESS';
export const FETCHED_ERROR = 'FETCHED_ERROR';


//CART ACTIONS
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const CHECKOUT = 'CHECKOUT';